import "./globals.css";
import React, {useState} from "react";
import React, {useEffect} from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  const [students, setStudents] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const API_BASE =
    process.env.NODE_ENV === "development"
      ? `http://localhost:8000`
      : process.env.NEXT_APP_BASE_URL;

  let ignore = false;
  useEffect(() => {
    if (!ignore) {
      getStudents();
    }

    return () => {
      ignore = true;
    };
  });

  const getStudents = async () => {
    try {
      await fetch(`${API_BASE}/students`)
        .then((res) => res.json())
        .then((data) => {
          setStudents(data);
        });
    } catch (error) {
      setError(error.message || "Unexpect Error");
    } finally {
      setLoading(false);
    }
  };
  return (
    <html lang="en">
      <body>
        <h1>students:</h1>
        <ul>
          <li></li>
        </ul>
      </body>
    </html>
  );
}
